/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dmzj_manhua_openapi_OpenApiHelper */

#ifndef _Included_com_dmzj_manhua_openapi_OpenApiHelper
#define _Included_com_dmzj_manhua_openapi_OpenApiHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dmzj_manhua_openapi_OpenApiHelper
 * Method:    onTokenReturn
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dmzj_manhua_openapi_OpenApiHelper_onTokenReturn
  (JNIEnv *, jclass, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
