/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dmzj_manhua_push_MessagePushTool */

#ifndef _Included_com_dmzj_manhua_push_MessagePushTool
#define _Included_com_dmzj_manhua_push_MessagePushTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dmzj_manhua_push_MessagePushTool
 * Method:    onMessageObtain
 * Signature: (Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dmzj_manhua_push_MessagePushTool_onMessageObtain
  (JNIEnv *, jclass, jobject, jstring, jstring, jstring);

JNIEXPORT void JNICALL Java_com_dmzj_manhua_push_MessagePushTool_onBaiduBind
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
